### ISSUE TITLE
Link to SDK not working, 404

### ISSUE THREAD

**Issue by alvarotech** [trywilco/wilcosdk#2]
**Describe the bug**
Link from the documentation is not working: https://www.trywilco.com/editorsdk
**To Reproduce**
1. Go to '[...](https://github.com/trywilco/wilcosdk)'
2. Click on the link to the SDK
3. See error 404

**Expected behavior**
Link opening the sdk

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EtiNoked** [comment]
Hey @alvarotech 
The new documentation can be found here: https://dev.trywilco.com/
All links are now working as expected. Thanks for reporting that issue
